language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t gsourav/my-first-docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true -t gsourav/my-first-docker-react-app npm run test
