version: '3'
services:
  react-web-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /new-react-app/node_modules
      - .:/new-react-app
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /new-react-app/node_modules
      - .:/new-react-app
    command: ["npm", "run", "test"]
